checkpoint:

model_type: resnet50

source: /mnt/media2/JuanBayona/DataSets/combined_datasets/train/histopathology

objective: /mnt/media2/JuanBayona/DataSets/combined_datasets/val_Reinhard

originals: /mnt/media2/JuanBayona/DataSets/combined_datasets/val/histopathology

batch_size: 64

num_workers: 8

output: results_reinhard
