checkpoint:

model_type: resnet50

source: /mnt/media2/JuanBayona/DataSets/combined_datasets/RINGS
objective: /mnt/media2/JuanBayona/DataSets/combined_datasets/CoCaHis

originals: 
batch_size: 64

num_workers: 8

output: results_rings_cocahis
